# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 679)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.base_data_path = QtWidgets.QLineEdit(self.groupBox)
        self.base_data_path.setObjectName("base_data_path")
        self.horizontalLayout.addWidget(self.base_data_path)
        self.base_data_btn = QtWidgets.QPushButton(self.groupBox)
        self.base_data_btn.setObjectName("base_data_btn")
        self.horizontalLayout.addWidget(self.base_data_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.item_data_path = QtWidgets.QLineEdit(self.groupBox)
        self.item_data_path.setObjectName("item_data_path")
        self.horizontalLayout_2.addWidget(self.item_data_path)
        self.item_data_btn = QtWidgets.QPushButton(self.groupBox)
        self.item_data_btn.setObjectName("item_data_btn")
        self.horizontalLayout_2.addWidget(self.item_data_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user_data_path = QtWidgets.QLineEdit(self.groupBox)
        self.user_data_path.setObjectName("user_data_path")
        self.horizontalLayout_4.addWidget(self.user_data_path)
        self.user_data_btn = QtWidgets.QPushButton(self.groupBox)
        self.user_data_btn.setObjectName("user_data_btn")
        self.horizontalLayout_4.addWidget(self.user_data_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.load_data_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_data_btn.setObjectName("load_data_btn")
        self.verticalLayout_2.addWidget(self.load_data_btn)
        self.verticalLayout_11.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.train_data_path = QtWidgets.QLineEdit(self.groupBox_5)
        self.train_data_path.setObjectName("train_data_path")
        self.horizontalLayout_20.addWidget(self.train_data_path)
        self.train_data_load_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.train_data_load_btn.setObjectName("train_data_load_btn")
        self.horizontalLayout_20.addWidget(self.train_data_load_btn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.svd_model_train_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.svd_model_train_btn.setObjectName("svd_model_train_btn")
        self.horizontalLayout_21.addWidget(self.svd_model_train_btn)
        self.save_svd_model_btn = QtWidgets.QPushButton(self.groupBox_5)
        self.save_svd_model_btn.setObjectName("save_svd_model_btn")
        self.horizontalLayout_21.addWidget(self.save_svd_model_btn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_21)
        self.verticalLayout_11.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 303))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.prediction_model_path = QtWidgets.QLineEdit(self.groupBox_7)
        self.prediction_model_path.setObjectName("prediction_model_path")
        self.horizontalLayout_15.addWidget(self.prediction_model_path)
        self.prediction_model_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.prediction_model_btn.setObjectName("prediction_model_btn")
        self.horizontalLayout_15.addWidget(self.prediction_model_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.preprocessing_cb = QtWidgets.QComboBox(self.groupBox_7)
        self.preprocessing_cb.setObjectName("preprocessing_cb")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.preprocessing_cb)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.preprocess_usage_matrix_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.preprocess_usage_matrix_btn.setObjectName("preprocess_usage_matrix_btn")
        self.horizontalLayout_3.addWidget(self.preprocess_usage_matrix_btn)
        self.save_dataset_btn = QtWidgets.QPushButton(self.groupBox_7)
        self.save_dataset_btn.setObjectName("save_dataset_btn")
        self.horizontalLayout_3.addWidget(self.save_dataset_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.f_dataset_path = QtWidgets.QLineEdit(self.groupBox_10)
        self.f_dataset_path.setObjectName("f_dataset_path")
        self.horizontalLayout_6.addWidget(self.f_dataset_path)
        self.f_dataset_load_btn = QtWidgets.QPushButton(self.groupBox_10)
        self.f_dataset_load_btn.setObjectName("f_dataset_load_btn")
        self.horizontalLayout_6.addWidget(self.f_dataset_load_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.verticalLayout_14.addWidget(self.groupBox_10)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.fc_dist_matrix_path = QtWidgets.QLineEdit(self.groupBox_6)
        self.fc_dist_matrix_path.setObjectName("fc_dist_matrix_path")
        self.horizontalLayout_13.addWidget(self.fc_dist_matrix_path)
        self.fc_dist_matrix_load_btn = QtWidgets.QPushButton(self.groupBox_6)
        self.fc_dist_matrix_load_btn.setObjectName("fc_dist_matrix_load_btn")
        self.horizontalLayout_13.addWidget(self.fc_dist_matrix_load_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sem_dist_matrix_path = QtWidgets.QLineEdit(self.groupBox_6)
        self.sem_dist_matrix_path.setObjectName("sem_dist_matrix_path")
        self.horizontalLayout_12.addWidget(self.sem_dist_matrix_path)
        self.sem_dist_matrix_load_btn = QtWidgets.QPushButton(self.groupBox_6)
        self.sem_dist_matrix_load_btn.setObjectName("sem_dist_matrix_load_btn")
        self.horizontalLayout_12.addWidget(self.sem_dist_matrix_load_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_11)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.alpha_edit = QtWidgets.QLineEdit(self.groupBox_11)
        self.alpha_edit.setObjectName("alpha_edit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alpha_edit)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.label_4 = QtWidgets.QLabel(self.groupBox_11)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.jaccard_rb = QtWidgets.QRadioButton(self.groupBox_11)
        self.jaccard_rb.setChecked(True)
        self.jaccard_rb.setObjectName("jaccard_rb")
        self.horizontalLayout_19.addWidget(self.jaccard_rb)
        self.wp_rb = QtWidgets.QRadioButton(self.groupBox_11)
        self.wp_rb.setObjectName("wp_rb")
        self.horizontalLayout_19.addWidget(self.wp_rb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.taxonomy_path = QtWidgets.QLineEdit(self.groupBox_11)
        self.taxonomy_path.setObjectName("taxonomy_path")
        self.horizontalLayout_7.addWidget(self.taxonomy_path)
        self.taxonomy_btn = QtWidgets.QPushButton(self.groupBox_11)
        self.taxonomy_btn.setObjectName("taxonomy_btn")
        self.horizontalLayout_7.addWidget(self.taxonomy_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addWidget(self.groupBox_11)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.filtering_methods_cb = QtWidgets.QComboBox(self.groupBox_2)
        self.filtering_methods_cb.setObjectName("filtering_methods_cb")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filtering_methods_cb)
        self.verticalLayout_12.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.process_filtering_technique_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.process_filtering_technique_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.process_filtering_technique_btn.setObjectName("process_filtering_technique_btn")
        self.horizontalLayout_5.addWidget(self.process_filtering_technique_btn)
        self.save_distance_matrix_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_distance_matrix_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.save_distance_matrix_btn.setObjectName("save_distance_matrix_btn")
        self.horizontalLayout_5.addWidget(self.save_distance_matrix_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_14.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.t_graph_view = QtWidgets.QGroupBox(self.tab_6)
        self.t_graph_view.setObjectName("t_graph_view")
        self.formLayout_6 = QtWidgets.QFormLayout(self.t_graph_view)
        self.formLayout_6.setObjectName("formLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.t_dataset_path = QtWidgets.QLineEdit(self.t_graph_view)
        self.t_dataset_path.setObjectName("t_dataset_path")
        self.horizontalLayout_8.addWidget(self.t_dataset_path)
        self.t_dataset_btn = QtWidgets.QPushButton(self.t_graph_view)
        self.t_dataset_btn.setObjectName("t_dataset_btn")
        self.horizontalLayout_8.addWidget(self.t_dataset_btn)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.t_dist_mat_path = QtWidgets.QLineEdit(self.t_graph_view)
        self.t_dist_mat_path.setObjectName("t_dist_mat_path")
        self.horizontalLayout_9.addWidget(self.t_dist_mat_path)
        self.t_dist_mat_btn = QtWidgets.QPushButton(self.t_graph_view)
        self.t_dist_mat_btn.setObjectName("t_dist_mat_btn")
        self.horizontalLayout_9.addWidget(self.t_dist_mat_btn)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.t_test_file_path = QtWidgets.QLineEdit(self.t_graph_view)
        self.t_test_file_path.setObjectName("t_test_file_path")
        self.horizontalLayout_10.addWidget(self.t_test_file_path)
        self.t_test_file_btn = QtWidgets.QPushButton(self.t_graph_view)
        self.t_test_file_btn.setObjectName("t_test_file_btn")
        self.horizontalLayout_10.addWidget(self.t_test_file_btn)
        self.formLayout_6.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.uu_radio_btn = QtWidgets.QRadioButton(self.t_graph_view)
        self.uu_radio_btn.setObjectName("uu_radio_btn")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.uu_radio_btn)
        self.ii_radio_btn = QtWidgets.QRadioButton(self.t_graph_view)
        self.ii_radio_btn.setObjectName("ii_radio_btn")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ii_radio_btn)
        self.label_11 = QtWidgets.QLabel(self.t_graph_view)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.threshold_edit = QtWidgets.QLineEdit(self.t_graph_view)
        self.threshold_edit.setObjectName("threshold_edit")
        self.formLayout_6.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.threshold_edit)
        self.verticalLayout_15.addWidget(self.t_graph_view)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.t_mae_label = QtWidgets.QLabel(self.groupBox_12)
        self.t_mae_label.setObjectName("t_mae_label")
        self.verticalLayout_7.addWidget(self.t_mae_label)
        self.t_rmse_label = QtWidgets.QLabel(self.groupBox_12)
        self.t_rmse_label.setObjectName("t_rmse_label")
        self.verticalLayout_7.addWidget(self.t_rmse_label)
        self.verticalLayout_15.addWidget(self.groupBox_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 204, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.t_test_btn = QtWidgets.QPushButton(self.tab_6)
        self.t_test_btn.setObjectName("t_test_btn")
        self.verticalLayout_15.addWidget(self.t_test_btn)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.c_dist_mat_btn_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.c_dist_mat_btn_1.setObjectName("c_dist_mat_btn_1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.c_dist_mat_btn_1)
        self.c_dist_mat_path_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.c_dist_mat_path_1.setObjectName("c_dist_mat_path_1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c_dist_mat_path_1)
        self.c_test_file_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.c_test_file_btn.setMaximumSize(QtCore.QSize(16777215, 25))
        self.c_test_file_btn.setObjectName("c_test_file_btn")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.c_test_file_btn)
        self.c_test_file_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.c_test_file_path.setObjectName("c_test_file_path")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.c_test_file_path)
        self.c_dataset_path = QtWidgets.QLineEdit(self.groupBox_3)
        self.c_dataset_path.setObjectName("c_dataset_path")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.c_dataset_path)
        self.c_dataset_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.c_dataset_btn.setObjectName("c_dataset_btn")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.c_dataset_btn)
        self.c_dist_mat_btn_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.c_dist_mat_btn_2.setObjectName("c_dist_mat_btn_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.c_dist_mat_btn_2)
        self.c_dist_mat_path_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.c_dist_mat_path_2.setObjectName("c_dist_mat_path_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.c_dist_mat_path_2)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_16.addWidget(self.label_5)
        self.kmedoids_cluster_count_edit = QtWidgets.QLineEdit(self.groupBox_9)
        self.kmedoids_cluster_count_edit.setObjectName("kmedoids_cluster_count_edit")
        self.horizontalLayout_16.addWidget(self.kmedoids_cluster_count_edit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.bso_check_box = QtWidgets.QCheckBox(self.groupBox_9)
        self.bso_check_box.setObjectName("bso_check_box")
        self.verticalLayout_9.addWidget(self.bso_check_box)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_17.addWidget(self.label_6)
        self.bso_max_iter_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.bso_max_iter_edit.setObjectName("bso_max_iter_edit")
        self.horizontalLayout_17.addWidget(self.bso_max_iter_edit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_18.addWidget(self.label_2)
        self.bso_flip_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.bso_flip_edit.setObjectName("bso_flip_edit")
        self.horizontalLayout_18.addWidget(self.bso_flip_edit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.kmedoids_run_btn = QtWidgets.QPushButton(self.groupBox_9)
        self.kmedoids_run_btn.setObjectName("kmedoids_run_btn")
        self.verticalLayout_9.addWidget(self.kmedoids_run_btn)
        self.kmedoids_mae_label = QtWidgets.QLabel(self.groupBox_9)
        self.kmedoids_mae_label.setObjectName("kmedoids_mae_label")
        self.verticalLayout_9.addWidget(self.kmedoids_mae_label)
        self.kmedoids_rmse_label = QtWidgets.QLabel(self.groupBox_9)
        self.kmedoids_rmse_label.setObjectName("kmedoids_rmse_label")
        self.verticalLayout_9.addWidget(self.kmedoids_rmse_label)
        self.horizontalLayout_11.addWidget(self.groupBox_9)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.k_edit = QtWidgets.QLineEdit(self.groupBox_8)
        self.k_edit.setObjectName("k_edit")
        self.horizontalLayout_14.addWidget(self.k_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.multiview_check_box = QtWidgets.QCheckBox(self.groupBox_8)
        self.multiview_check_box.setObjectName("multiview_check_box")
        self.verticalLayout.addWidget(self.multiview_check_box)
        spacerItem5 = QtWidgets.QSpacerItem(20, 109, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.knn_run_btn = QtWidgets.QPushButton(self.groupBox_8)
        self.knn_run_btn.setObjectName("knn_run_btn")
        self.verticalLayout.addWidget(self.knn_run_btn)
        self.knn_mae_label = QtWidgets.QLabel(self.groupBox_8)
        self.knn_mae_label.setObjectName("knn_mae_label")
        self.verticalLayout.addWidget(self.knn_mae_label)
        self.knn_rmse_label = QtWidgets.QLabel(self.groupBox_8)
        self.knn_rmse_label.setObjectName("knn_rmse_label")
        self.verticalLayout.addWidget(self.knn_rmse_label)
        self.horizontalLayout_11.addWidget(self.groupBox_8)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.verticalLayout_5.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status_label.setText(_translate("MainWindow", ":D"))
        self.groupBox.setTitle(_translate("MainWindow", "Load DaTaSet"))
        self.base_data_btn.setText(_translate("MainWindow", "base data"))
        self.item_data_btn.setText(_translate("MainWindow", "item data"))
        self.user_data_btn.setText(_translate("MainWindow", "user data"))
        self.load_data_btn.setText(_translate("MainWindow", "load data"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Create SVD model"))
        self.train_data_load_btn.setText(_translate("MainWindow", "Load Training Data"))
        self.svd_model_train_btn.setText(_translate("MainWindow", "Train"))
        self.save_svd_model_btn.setText(_translate("MainWindow", "Save"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Preprocessing"))
        self.prediction_model_btn.setText(_translate("MainWindow", "Model"))
        self.label_7.setText(_translate("MainWindow", "Preprocessing :"))
        self.preprocess_usage_matrix_btn.setText(_translate("MainWindow", "Process"))
        self.save_dataset_btn.setText(_translate("MainWindow", "Save Dataset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Data preprocessing"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Load Usage Matrix / Item Matrix"))
        self.f_dataset_load_btn.setText(_translate("MainWindow", "dataset"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Hybrid Parameters"))
        self.fc_dist_matrix_load_btn.setText(_translate("MainWindow", "CF"))
        self.sem_dist_matrix_load_btn.setText(_translate("MainWindow", "Semantic"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Additional parameters"))
        self.label_10.setText(_translate("MainWindow", "Alpha value (Only considered with weighted hybrid technique) :"))
        self.label_4.setText(_translate("MainWindow", "Semantic Filtering Parameters: "))
        self.jaccard_rb.setText(_translate("MainWindow", "Jaccard"))
        self.wp_rb.setText(_translate("MainWindow", "Wu Palmer"))
        self.taxonomy_btn.setText(_translate("MainWindow", "Taxonomy"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Apply Filtering Technigue CF/Semantic"))
        self.label.setText(_translate("MainWindow", "Filtering Algorithms :"))
        self.process_filtering_technique_btn.setText(_translate("MainWindow", "Process"))
        self.save_distance_matrix_btn.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Filtering Data"))
        self.t_graph_view.setTitle(_translate("MainWindow", "Load Inputs"))
        self.t_dataset_btn.setText(_translate("MainWindow", "Load Dataset"))
        self.t_dist_mat_btn.setText(_translate("MainWindow", "Distance Matrix"))
        self.t_test_file_btn.setText(_translate("MainWindow", "Test File"))
        self.uu_radio_btn.setText(_translate("MainWindow", "user/user"))
        self.ii_radio_btn.setText(_translate("MainWindow", "item/item"))
        self.label_11.setText(_translate("MainWindow", "Threshold"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Results"))
        self.t_mae_label.setText(_translate("MainWindow", "MAE"))
        self.t_rmse_label.setText(_translate("MainWindow", "RMSE"))
        self.t_test_btn.setText(_translate("MainWindow", "TEST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Test without Classification"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Load inputs"))
        self.c_dist_mat_btn_1.setText(_translate("MainWindow", "Load distance matrix 1"))
        self.c_test_file_btn.setText(_translate("MainWindow", "Load Test File"))
        self.c_dataset_btn.setText(_translate("MainWindow", "Load Dataset"))
        self.c_dist_mat_btn_2.setText(_translate("MainWindow", "Load distance matrix 2"))
        self.groupBox_9.setTitle(_translate("MainWindow", "K-medoids"))
        self.label_5.setText(_translate("MainWindow", "Number of Clusters :"))
        self.bso_check_box.setText(_translate("MainWindow", "Run with BSO optimisation"))
        self.groupBox_4.setTitle(_translate("MainWindow", "BSO Params"))
        self.label_6.setText(_translate("MainWindow", "Max iterations :"))
        self.label_2.setText(_translate("MainWindow", "Flip Param :"))
        self.kmedoids_run_btn.setText(_translate("MainWindow", "Run"))
        self.kmedoids_mae_label.setText(_translate("MainWindow", "MAE"))
        self.kmedoids_rmse_label.setText(_translate("MainWindow", "RMSE"))
        self.groupBox_8.setTitle(_translate("MainWindow", "KNN"))
        self.label_8.setText(_translate("MainWindow", "k neighbours:"))
        self.multiview_check_box.setText(_translate("MainWindow", "Run with Multiview"))
        self.knn_run_btn.setText(_translate("MainWindow", "Run"))
        self.knn_mae_label.setText(_translate("MainWindow", "MAE"))
        self.knn_rmse_label.setText(_translate("MainWindow", "RMSE"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Classification algorithms"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Classification and Optimization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

